### ISSUE TITLE
Training and testing

### ISSUE THREAD

**Issue by Zumbalamambo** [GuansongPang/deviation-network#1]
How do I train or test the code?

**Comment by GuansongPang** [comment]
The detail of training and testing DevNet can ben found in the rundevnet function. See Lines 335-349 in devnet.py for the training and testing parameters.

**Comment by Zumbalamambo** [comment]
@GuansongPang which dataset did you use? Please share some details on dataset, training and inference

**Comment by GuansongPang** [comment]
Please see the experiments section and the reproducibility material in our paper for this information
