### ISSUE TITLE
Model performance

### ISSUE THREAD

**Issue by natuhvnh** [GuansongPang/deviation-network#4]
Hi,
I run the code but dont get the performance reported in the paper with Credit card default dataset:
AUC-ROC: 0.6005, AUC-PR: 0.1028 (last run)
average AUC-ROC: 0.6429, average AUC-PR: 0.0941
Did you feature engineering or change default arguments to get the best performance for this dataset (I trained model with default arguments) ?

**Comment by GuansongPang** [comment]
> Hi,
> I run the code but dont get the performance reported in the paper with Credit card default dataset:
> AUC-ROC: 0.6005, AUC-PR: 0.1028 (last run)
> average AUC-ROC: 0.6429, average AUC-PR: 0.0941
> Did you feature engineering or change default arguments to get the best performance for this dataset (I trained model with default arguments) ?

Hi, 
Thanks for your interest. Before applying DevNet, some standard data preprocessing steps were performed, including feature rescaling into the range [0, 1] and missing value replacement with the mean. All the reported results are based on the default settings.

**Comment by natuhvnh** [comment]
Thank you. I got it.
