### ISSUE TITLE
Reproduce for a different dataset

### ISSUE THREAD

**Issue by faaizuddin** [GuansongPang/deviation-network#5]
Hello,
I have a 1d time series dataset in the format (x, y, z), where x = number of samples, y = number of timesteps and z = 1 (dimensions).
How am I able to run your code with my dataset? Where do I need to make changes?

**Comment by GuansongPang** [comment]
Hi, a simple solution would be to add some additional network layers that are suitable for handling time series data into the current DevNet architecture, such as simple RNN, LSTM, GRU, etc. Thanks.
