### ISSUE TITLE
Interpretability of anomaly scores

### ISSUE THREAD

**Issue by ThisisHubert** [GuansongPang/deviation-network#9]
In terms of interpretability of the anomaly scores, can we also get the contribution of each feature importances of the datasets (columns) from the Z-Score-based deviation loss ?

**Comment by ThisisHubert** [comment]
As far as I've known, we have to use framework like shap or lime to get this kind of parameter

**Comment by GuansongPang** [comment]
> As far as I've known, we have to use framework like shap or lime to get this kind of parameter

Hi,

You may refer to the journal extension of the paper at https://github.com/Choubo/deviation-network-image, where you can find how we can get feature importance w.r.t. the deviation-based anomaly scores. 

We focus on image data in the journal version, so the feature importance is the importance of pixels for image data.

**Comment by ThisisHubert** [comment]
I see. Will take a look and will comment more if more explanation is needed. Thank you for the swift response

**Comment by ThisisHubert** [comment]
@GuansongPang Could you please point out which file specifically show this information ? I'm slightly loss

**Comment by ThisisHubert** [comment]
Do you have example for tabular data important feature selection ?

**Comment by Aml-Hassan-Abd-El-hamid** [comment]
Hi @ThisisHubert 
did you find an example of tabular data's important feature selection ? and if you did, do you mind sharing it?
